"""Compatibility exports for the source-independent Queue CSV contract."""

from alma_duplicate.queue_csv_contract import (
    QUEUE_BANDWIDTH_COLUMNS,
    QUEUE_CONTRACT_VERSION,
    QUEUE_DICTIONARY_ALIASES,
    QUEUE_DICTIONARY_ONLY_FIELDS,
    QUEUE_EVIDENCE_SNAPSHOT_SHA256,
    QUEUE_EXPECTED_COLUMNS,
    QUEUE_EXPECTED_SECONDARY_HEADER,
    QUEUE_FIELD_SPECS,
    QUEUE_FREQUENCY_COLUMNS,
    QUEUE_MOSAIC_ZERO_TOLERANCE_ARCSEC,
    QUEUE_REFERENCE_INTERVAL_TOLERANCE_GHZ,
    QUEUE_SCALAR_COLUMNS,
    QUEUE_SCHEMA_VERSION,
    QUEUE_SPECTRAL_RESOLUTION_COLUMNS,
    QUEUE_SPS_COLUMNS,
    QUEUE_SPW_COLUMNS,
    QUEUE_SPW_SLOT_COUNT,
    QueueFieldKind,
    QueueFieldScope,
    QueueFieldSpec,
    QueueMetadataStatus,
    QueueSpwColumns,
    SecondaryTokenKind,
    classify_secondary_token,
    spw_columns,
)

__all__ = [
    "QUEUE_BANDWIDTH_COLUMNS",
    "QUEUE_CONTRACT_VERSION",
    "QUEUE_DICTIONARY_ALIASES",
    "QUEUE_DICTIONARY_ONLY_FIELDS",
    "QUEUE_EVIDENCE_SNAPSHOT_SHA256",
    "QUEUE_EXPECTED_COLUMNS",
    "QUEUE_EXPECTED_SECONDARY_HEADER",
    "QUEUE_FIELD_SPECS",
    "QUEUE_FREQUENCY_COLUMNS",
    "QUEUE_MOSAIC_ZERO_TOLERANCE_ARCSEC",
    "QUEUE_REFERENCE_INTERVAL_TOLERANCE_GHZ",
    "QUEUE_SCALAR_COLUMNS",
    "QUEUE_SCHEMA_VERSION",
    "QUEUE_SPECTRAL_RESOLUTION_COLUMNS",
    "QUEUE_SPS_COLUMNS",
    "QUEUE_SPW_COLUMNS",
    "QUEUE_SPW_SLOT_COUNT",
    "QueueFieldKind",
    "QueueFieldScope",
    "QueueFieldSpec",
    "QueueMetadataStatus",
    "QueueSpwColumns",
    "SecondaryTokenKind",
    "classify_secondary_token",
    "spw_columns",
]
